services:
  simple-spaceapi:
    build: .
    ports:
      - "1337:1337"
    volumes:
      - ./data/base:/app/data/base
      - ./data/uploads:/app/public/uploads
    env_file:
      - .env
    environment:                                                                  │
      - PORT=1337                                                                 │
    restart: unless-stopped
