services:
  simple-spaceapi:
    build: .
    ports:
      - "1337:1337"
    volumes:
      - ./data/base:/app/data/base
      - ./data/uploads:/app/public/uploads
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=1337
      - DATABASE_CLIENT=sqlite
      - DATABASE_FILENAME=data/base/sqlite.db
      - NODE_ENV=production
      - STRAPI_TELEMETRY_DISABLED=true
    restart: unless-stopped
